spring:
  application:
    name: productservice
  data:
    cassandra:
      keyspace-name: productdatabase
      port: 9042
      contact-points:
        - host1
        - host2
      username: cassandra
      password: cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ken4ward/configserver
          username: ken4ward
          password: g201115@...Adei
          clone-on-start: true